### PR TITLE
#166240809 Configure Authors to use PostgreSQL as DB Engine

### PR DESCRIPTION
**Pull request by Ramadhan0**
#### What does this PR do?
configure the project to use Postgres as a database engine 
#### Description of Task to be completed?
setting up the following environment
1. Development Environment:  local database for project development purposes.
2. Test Environment: local database for project testing purposes only.
3. Staging Environment: for staging heroku app purpose.
4. Production Environment: for the finished backEnd Product.
#### How should this be manually tested?
clone repo 
npm install
npm run dev
#### What are the relevant pivotal tracker stories?
[#166240809](https://www.pivotaltracker.com/story/show/166240809)

### CODE REVIEW

**Review by bdushimi — CHANGES_REQUESTED** [review]
Squash your commit messages into fewer meaningful messages. You got duplicated messages.

**Review by nkpremices — CHANGES_REQUESTED** [review]
Can you please squash your commits into two? and please implement @bdushimi commits

**Review by bdushimi — CHANGES_REQUESTED** [review]
A couple of things you may want to change:
1. What does this PR do: If you think about it, a user hasn't and should not have knowledge of a DB engine they're using.
2. The description of the task to be completed is not clear!

**Review by alainburindi — APPROVED** [review]

**Review by nkpremices — CHANGES_REQUESTED** [review]
Looks fine for me

**Review by nkpremices — APPROVED** [review]
looks fine now

**Comment by bdushimi** [comment]
But I can still see the merge conflicts!

**Comment by nkpremices** [comment]
> But I can still see the merge conflicts!

These conflicts are there because the PR of @truestbyheart was merged. Please @Ramadhan0 resolve these conflicts

**Review by nkpremices — APPROVED** [review]
Looks fine now

**Pull request merged**
