### PR TITLE
#166494346 fix deploy to heroku issue

### PR DESCRIPTION
**Pull request by alainburindi**
#### What does this PR do?
Fix the deployment process to heroku
#### How should this be manually tested?
for development process access the endpoints using this link https://savage-rangers-ah-staging.herokuapp.com/
for deployment process use this link https://savage-rangers-ah.herokuapp.com/
#### What are the relevant pivotal tracker stories?
[#166494346](https://www.pivotaltracker.com/story/show/166494346)

### CODE REVIEW

**Comment by bdushimi** [comment]
Could you please name this PR appropriately?

**Comment by alainburindi** [comment]
> Could you please name this PR appropriately?

check it up

**Review by nkpremices — CHANGES_REQUESTED** [review]
Can you please squash your commits into at least three ?

**Review by MCFrank16 — APPROVED** [review]
Coup de chapeau @alainburindi

**Review by truestbyheart — COMMENTED** [review]
add ```npm coverage``` after script but all in all, everything looks fine

**Comment by alainburindi** [comment]
> add `npm coverage` after script but all in all, everything looks fine

I think it will be added after merging!! can you explain?

**Comment by truestbyheart** [comment]
the script is not even in the merged changes

**Comment by alainburindi** [comment]
> the script is not even in the merged changes
now it's done

**Review by nkpremices — APPROVED** [review]
Looks fine now

**Pull request merged**
